### ISSUE TITLE
MYSelectionHandler parameter can't cast UITableViewCell.

### ISSUE THREAD

**Issue by dekatotoro** [nghialv/Hakuba#2]
Hi,  Thanks for writing this great Library.

There is that one in trouble, It would help us if you would be compatible in the future.

MYSelectionHandler parameter is MYBaseViewProtocol.
I want to use the view of cell in the handler, but MYBaseViewProtocol can't cast UIView.
Is not possible to change the IF of MYSelectionHandler to MYBaseViewProtocol of class that inherits from UIView?

It is expected the correspondence.
Thank you.

**Comment by dekatotoro** [comment]
Hi 

I'm sorry.
 I can get cell in handler.

```
selectionHandler: { (cellView: MYBaseViewProtocol) in
    let cell = cellView as MYTableViewCell
} )
```

Thank you.

**Comment by nghialv** [comment]
:+1:
