### ISSUE TITLE
HeaderFooterView height, and backgroundColor

### ISSUE THREAD

**Issue by remirobert** [nghialv/Hakuba#43]
Hello, I need to use an HeaderFooterView on a Section.

I created a model view : 

``` swift
class HeaderSectionTripViewModel: HeaderFooterViewModel {

    init() {
        super.init(view: HeaderSectionTrip.self)
    }
}
```

and then my HeaderFooterView view : 

``` swift
class HeaderSectionTrip: HeaderFooterView, HeaderFooterViewType {
    typealias ViewModel = HeaderFooterViewModel

    override func configure() {
    }
}
```

Now this how I add my section header : 

``` swift
self.hakuba.registerHeaderFooterByNib(HeaderSectionTrip.self)

let section = Section()
section.header = HeaderSectionTripViewModel()
self.hakuba.append(section)
```

But my HeaderView is transparent. And also I need to change the height.
thanks in advance for your help.

**Comment by nghialv** [comment]
Hi @remirobert . If you want to set height and backgroundColor you can see the following codes.

```
class HeaderSectionTripViewModel: HeaderFooterViewModel {
    init() {
        super.init(view: HeaderSectionTrip.self)
        height = 50
    }
}

class HeaderSectionTrip: HeaderFooterView, HeaderFooterViewType {
    typealias ViewModel = HeaderFooterViewModel

    override func awakeFromNib() {
          super.awakeFromNib()
          backgroundColor = .yourColor()
    }

    override func configure() {
    }
}
```

**Comment by remirobert** [comment]
@nghialv thank you so much for your help !! It works

**Comment by remirobert** [comment]
I am back for add more precision about this issue.

[http://stackoverflow.com/questions/15604900/uitableviewheaderfooterview-unable-to-change-background-color](url)

In fact you need to had an another UIView, acting like a container.
That's it. 🙀⚠️🎉
